### ISSUE TITLE
执行main.py第三个功能时出错

### ISSUE THREAD

**Issue by Delivil** [SunsetYe66/ClasstableToIcal#2]
请输入要进入的功能：3
请输入第一周周一的日期，格式为 YYYYMMDD，如 20200224：20200224
请输入提前提醒时间，以分钟计；若不需要提醒请输入 N：20
文件头写入成功！
第1条课程信息写入成功！
Traceback (most recent call last):
  File ".\main.py", line 57, in <module>
    main(i)
  File ".\main.py", line 48, in main
    gen_ical()
  File ".\main.py", line 25, in gen_ical
    process.main_process()
  File "C:\Users\Administrator\OneDrive\Base\code\python\project\ClasstableToIcal-master\ical_generator.py", line 139, in main_process
    self.class_timetable[str(int(obj['ClassTimeId']))]["startTime"]
KeyError: '7'
环境：Python 3.7.0，Windows 10 x64

**Comment by SunsetYe66** [comment]
请检查 conf_classTime 中是否有 id 为 7 的上下课时间段

**Comment by Delivil** [comment]
> 请检查 conf_classTime 中是否有 id 为 7 的上下课时间段

谢谢！是我个人犯傻了！没有注意到classTime的ID，直接使用第几节课的数字！
再次感谢！
